services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Americas/Sao_Paulo
    volumes:
      - ../../data/raddar:/config
      - ../../data/deluge/downloads:/downloads #optional
      - ../../data/multimedia/movies:/movies #optional
      - ../../data/multimedia/series:/series #optional
      - ../../data/multimedia/manga:/manga #optional
      - ../../data/multimedia/books:/books #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    labels:
      - io.portainer.accesscontrol.public