services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ../../data/sonnar/config:/config
      - ../../data/multimedia/series:/series #optional
      - ../../data/multimedia/movies:/movies #optional
      - ../../data/multimedia/books:/books #optional
      - ../../data/multimedia/movies:/manga #optional
    ports:
      - 8765:8989
    restart: unless-stopped
    labels:
      - io.portainer.accesscontrol.public
