services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - ../../data/jellyfin/config:/config
      - ../../data/jellyfin/cache:/cache
      - type: bind
        source: ../../data/multimedia/series
        target: /series
      - type: bind
        source: ../../data/multimedia/movies
        target: /movies
      - type: bind
        source: ../../data/multimedia/books
        target: /books
      - type: bind
        source: ../../data/multimedia/manga
        target: /manga
    restart: 'unless-stopped'
  
